global:
  scrape_interval:     1s
  evaluation_interval: 1s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['47.100.127.55:9090']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['47.100.127.55:8899']
  - job_name: 'node'
    static_configs:
      - targets: ['47.100.127.55:9100']
  - job_name: 'austin'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['47.100.127.55:8888']